src/Entity/Hotel.php
<?php

namespace App\Entity;

use App\Repository\HotelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HotelRepository::class)
 */
class Hotel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $prix;

    /**
     * @ORM\OneToMany(targetEntity=ReservationHotel::class, mappedBy="hotel")
     */
    private $Hotel;

    public function __construct()
    {
        $this->Hotel = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Collection<int, ReservationHotel>
     */
    public function getHotel(): Collection
    {
        return $this->Hotel;
    }

    public function addHotel(ReservationHotel $hotel): self
    {
        if (!$this->Hotel->contains($hotel)) {
            $this->Hotel[] = $hotel;
            $hotel->setHotel($this);
        }

        return $this;
    }

    public function removeHotel(ReservationHotel $hotel): self
    {
        if ($this->Hotel->removeElement($hotel)) {
            // set the owning side to null (unless already changed)
            if ($hotel->getHotel() === $this) {
                $hotel->setHotel(null);
            }
        }

        return $this;
    }
}

src/Entity/ReservationTour.php
<?php

namespace App\Entity;

use App\Repository\ReservationTourRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationTourRepository::class)
 */
class ReservationTour
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDepart;

    /**
     * @ORM\Column(type="date")
     */
    private $dateFin;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbrPersonne;

    /**
     * @ORM\ManyToOne(targetEntity=TourPackage::class, inversedBy="TourPackage")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tourPackage;

    /**
     * @ORM\OneToOne(targetEntity=Payement::class, mappedBy="peyementTour", cascade={"persist", "remove"})
     */
    private $payement;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tourReservation")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=3)
     */
    private $Total;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->dateDepart;
    }

    public function setDateDepart(\DateTimeInterface $dateDepart): self
    {
        $this->dateDepart = $dateDepart;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getNbrPersonne(): ?int
    {
        return $this->nbrPersonne;
    }

    public function setNbrPersonne(int $nbrPersonne): self
    {
        $this->nbrPersonne = $nbrPersonne;

        return $this;
    }

    public function getTourPackage(): ?TourPackage
    {
        return $this->tourPackage;
    }

    public function setTourPackage(?TourPackage $tourPackage): self
    {
        $this->tourPackage = $tourPackage;

        return $this;
    }

    public function getPayement(): ?Payement
    {
        return $this->payement;
    }

    public function setPayement(Payement $payement): self
    {
        // set the owning side of the relation if necessary
        if ($payement->getPeyementTour() !== $this) {
            $payement->setPeyementTour($this);
        }

        $this->payement = $payement;

        return $this;
    }

    public function getClient(): ?User
    {
        return $this->client;
    }

    public function setClient(?User $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->Total;
    }

    public function setTotal(string $Total): self
    {
        $this->Total = $Total;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Cet email est déjà utilisé.")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $nomPrenom;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @Assert\Length(
     *      min = 5,
     *      minMessage=" Entrer un mot de passe au mini de 5 caracteres"
     *
     *     )
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="date")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Numtel;

    /**
     * @ORM\OneToMany(targetEntity=Reviews::class, mappedBy="Client")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=ReservationFlight::class, mappedBy="clientId", orphanRemoval=true)
     */
    private $flightReservation;

    /**
     * @ORM\OneToMany(targetEntity=ReservationHotel::class, mappedBy="client", orphanRemoval=true)
     */
    private $hotelReservation;

    /**
     * @ORM\OneToMany(targetEntity=ReservationTour::class, mappedBy="client", orphanRemoval=true)
     */
    private $tourReservation;
    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     */
    private $reset_token;

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->flightReservation = new ArrayCollection();
        $this->hotelReservation = new ArrayCollection();
        $this->tourReservation = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNomPrenom(): ?string
    {
    return $this->nomPrenom;
    }

    public function setNomPrenom(string $nomPrenom): self
    {
    $this->nomPrenom = $nomPrenom;

    return $this;
    }


    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return $this->roles;

    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getNumtel(): ?string
    {
        return $this->Numtel;
    }

    public function setNumtel(string $Numtel): self
    {
        $this->Numtel = $Numtel;

        return $this;
    }

    /**
     * @return Collection<int, reviews>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(reviews $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setClient($this);
        }

        return $this;
    }

    public function removeUser(reviews $user): self
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getClient() === $this) {
                $user->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ReservationFlight>
     */
    public function getFlightReservation(): Collection
    {
        return $this->flightReservation;
    }

    public function addFlightReservation(ReservationFlight $flightReservation): self
    {
        if (!$this->flightReservation->contains($flightReservation)) {
            $this->flightReservation[] = $flightReservation;
            $flightReservation->setClientId($this);
        }

        return $this;
    }

    public function removeFlightReservation(ReservationFlight $flightReservation): self
    {
        if ($this->flightReservation->removeElement($flightReservation)) {
            // set the owning side to null (unless already changed)
            if ($flightReservation->getClientId() === $this) {
                $flightReservation->setClientId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ReservationHotel>
     */
    public function getHotelReservation(): Collection
    {
        return $this->hotelReservation;
    }

    public function addHotelReservation(ReservationHotel $hotelReservation): self
    {
        if (!$this->hotelReservation->contains($hotelReservation)) {
            $this->hotelReservation[] = $hotelReservation;
            $hotelReservation->setClient($this);
        }

        return $this;
    }

    public function removeHotelReservation(ReservationHotel $hotelReservation): self
    {
        if ($this->hotelReservation->removeElement($hotelReservation)) {
            // set the owning side to null (unless already changed)
            if ($hotelReservation->getClient() === $this) {
                $hotelReservation->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ReservationTour>
     */
    public function getTourReservation(): Collection
    {
        return $this->tourReservation;
    }

    public function addTourReservation(ReservationTour $tourReservation): self
    {
        if (!$this->tourReservation->contains($tourReservation)) {
            $this->tourReservation[] = $tourReservation;
            $tourReservation->setClient($this);
        }

        return $this;
    }

    public function removeTourReservation(ReservationTour $tourReservation): self
    {
        if ($this->tourReservation->removeElement($tourReservation)) {
            // set the owning side to null (unless already changed)
            if ($tourReservation->getClient() === $this) {
                $tourReservation->setClient(null);
            }
        }

        return $this;
    }
//to assign roles
    public function assignRoles($userType): self
    {
        if ($userType === 'admin') {
            $this->roles = ['ROLE_ADMIN'];
        } elseif ($userType === 'client') {
            $this->roles = ['ROLE_CLIENT'];
        }
        return $this;
    }
    public function addRole($role): self
    {
        if (!in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
        }

        return $this;
    }
    public function removeRole($role): self
    {
        $key = array_search($role, $this->roles, true);
        if ($key !== false) {
            unset($this->roles[$key]);
            $this->roles = array_values($this->roles); // Reindex the array
        }

        return $this;
    }
    /**
     * @return mixed
     */
    public function getResetToken()
    {
        return $this->reset_token;
    }

    /**
     * @param mixed $reset_token
     */
    public function setResetToken($reset_token): void
    {
        $this->reset_token = $reset_token;
    }
}

src/Controller/PayementController.php
<?php

namespace App\Controller;

use App\Entity\ReservationTour;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Payement; // Updated entity
use App\Form\PaymentType; // Form should already be imported correctly
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityManagerInterface;
/**
 * @Route("/Payment")
 */
class PayementController extends AbstractController
{
    /**
     * @Route("/new", name="payment_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reservationId = $request->query->get('reservationId');
        
        $reservation = $entityManager->getRepository(ReservationTour::class)->find($reservationId);
        
        if (!$reservation) {
            $this->addFlash('error', 'Reservation not found.');
            return $this->redirectToRoute('home');
        }
        
        $payment = new Payement();
        $payment->setprixTotal($reservation->getTotal()); // Set total price from reservation
        
        $form = $this->createForm(PaymentType::class, $payment);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $payment->setPeyementTour($reservation);
            $entityManager->persist($payment);
            $entityManager->flush();
        
            $this->addFlash('success', 'Payement successful!');
            return $this->redirectToRoute('payment_success');
        }
        
        return $this->render('payement/new.html.twig', [
            'form' => $form->createView(),
            'reservation' => $reservation,
        ]);
    }
    /**
     * @Route("/success", name="payment_success")
     */
    public function success(): Response
    {
        return $this->render('payement/success.html.twig');
    }
    }

templates/payement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PaymentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/LastVersion/src/Controller/PaymentController.php'|file_link(0) }}">src/Controller/PaymentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/LastVersion/templates/payment/index.html.twig'|file_link(0) }}">templates/payment/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/payement/new.html.twig
{% block title %}{% endblock %}

{% block body %}
<style>
    /* Additional styles */
    /* Your additional styles can go here */
    /* For example: */
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        background-color: #f4ffe0;
    }
    .form-container {
        background-color: #f9f9f9; /* Light gray background */
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 600px; /* Limit the width */
        width: 100%; /* Ensure responsiveness */
    }
    .form-header {
        text-align: center;
        margin-bottom: 20px;
    }
    .form-header img {
        max-width: 100px;
    }
    .form-header h1 {
        margin: 0;
        color: #7c9e3d; /* Form title color */
    }
    .form-label {
        color: #555; /* Dark gray label text color */
        font-weight: bold;
        margin-bottom: 5px;
    }
    .form-textbox {
        width: 100%;
        padding: 10px;
        border: 1px solid #ddd; /* Light gray border color */
        border-radius: 4px;
        box-sizing: border-box;
        background-color: #f9f9f9; /* Match form container background */
        margin-bottom: 10px; /* Add margin between inputs */
    }
    .form-textbox:focus {
        border-color: #7c9e3d; /* Change border color on focus */
    }
    .submit-button {
        background-color: #4caf50; /* Green button color */
        color: white; /* White text color */
        border-radius: 6px; /* Rounded corners */
        transition: background-color 0.3s; /* Smooth transition */
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        font-size: 16px;
    }
    .submit-button:hover {
        background-color: #45a049; /* Darker green on hover */
    }
</style>

<div class="form-container">
    <div class="form-header">
        <img src="{{ asset('imag/cap.png') }}" alt="Logo">
        <h1>Formulaire de paiement</h1>
    </div>

    <h2>Reservation Details</h2>
    <p><strong>Name:</strong> {{ reservation.tourPackage.nom }}</p>
    <p><strong>Description:</strong> {{ reservation.tourPackage.description }}</p>
    <p><strong>Start Date:</strong> {{ reservation.dateDepart|date('Y-m-d') }}</p>
    <p><strong>End Date:</strong> {{ reservation.dateFin|date('Y-m-d') }}</p>
    <p><strong>Number of Persons:</strong> {{ reservation.nbrPersonne }}</p>
    <p><strong>Total Price:</strong> {{ reservation.total }} €</p>

    {{ form_start(form) }}

    <label class="form-label">Nom prénom</label>
    {{ form_widget(form.NomPrenom, {'attr': {'class': 'form-textbox'}}) }}

    <label class="form-label">Adresse</label>
    {{ form_widget(form.adresse, {'attr': {'class': 'form-textbox'}}) }}

    <label class="form-label">Téléphone</label>
    {{ form_widget(form.numtel, {'attr': {'class': 'form-textbox'}}) }}

    <label class="form-label">Méthode de paiement</label>
    {{ form_widget(form.methodePayement, {'attr': {'class': 'form-textbox'}}) }}

    <label class="form-label">Numéro de carte</label>
    {{ form_widget(form.numCarte, {'attr': {'class': 'form-textbox'}}) }}

    <label class="form-label">Code de sécurité</label>
    {{ form_widget(form.codeSecurite, {'attr': {'class': 'form-textbox'}}) }}

    <button type="submit" class="submit-button">Confirmer le paiement</button>

    {{ form_end(form) }}
</div>
{% endblock %}

templates/payement/success.html.twig
{% block title %}Payment Success{% endblock %}

{% block body %}
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4ffe0;
            margin: 0;
            padding: 0;
        }
        .success-container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            text-align: center;
        }
        .success-container h1 {
            color: #7c9e3d;
            margin-bottom: 20px;
        }
        .success-container p {
            color: #333;
            margin-bottom: 10px;
        }
        .success-container .thank-you {
            font-weight: bold;
        }
        .success-container .button-container {
            margin-top: 20px;
        }
        .success-container .button-container a {
            display: inline-block;
            padding: 10px 20px;
            margin: 5px;
            color: #fff;
            background-color: #7c9e3d;
            border-radius: 5px;
            text-decoration: none;
        }
        .success-container .button-container a:hover {
            background-color: #6a8833;
        }
    </style>

    <div class="success-container">
        <h1>Payment Successful!</h1>
        <p>Your payment has been successfully processed.</p>
        <p class="thank-you">Thank you for your purchase!</p>
        <div class="button-container">
            <a href="{{ path('home') }}" class="home-button">Go to Home</a>
            <a href="{{ path('client_reservation') }}" class="reservation-button">View Reservations</a>
        </div>
    </div>
{% endblock %}